#!/usr/bin/perl
use strict;

my $s = 0;

# loop until the end of standard input
while(<>) {
    # add all numbers in a line
    $s += $_ for split /\s+/ while <>;
}

# print out the sum
print "$s\n";

=head1 NAME

sum - compute the sum.

=head1 SYNOPSIS

B<sum> < I<file>

cat I<file> | B<sum>
    
=head1 DESCRIPTION

Computes the sum of decimal numbers piped in from the
standard input and separated by spaces, tabs, and/or newlines.

=head1 AUTHOR

Val Tenyotkin B<<val@tenyotk.in>>

=cut
