#!/usr/bin/perl
use strict;

my ($s, $n) = (0, 0);

# loop until the end of standard input
while(<>) {
    # add all numbers in a line
    ++$n and $s += $_ for split /\s+/;
}

# compute the mean
$s /= $n;

# print the mean
print "$s\n";

=head1 NAME

mean - compute the mean.

=head1 SYNOPSIS

B<mean> < I<file>

cat I<file> | B<mean>
    
=head1 DESCRIPTION

Computes the mean of a list of decimal numbers piped in from the
standard input and separated by spaces, tabs, and/or newlines.

=head1 AUTHOR

Val Tenyotkin B<<val@tenyotk.in>>

=cut
