#!/bin/bash

function minify() {
    # remove newlines
    # remove comments
    # remove spaces between tags
    echo "$1" \
    | tr -d "\n" \
    | perl -pe "s/<!--.*?-->//g" \
    | perl -pe "s/\s*([<>])\s*/\1/g"
}

# if a valid file is supplied, use it
if [ -f "$1" ]
then
    # we can minify that!
    minify "`cat $1`"
#if not, attempt to use the standard input
else
    # loop through the lines
    while read LINE
    do
        # store the line
        css=${css}${LINE}
    done
    # we can minify that!
    minify "${css}"
fi
