#!/bin/bash

# TO DO: do not alter anything within quotes

function minify() {
    # remove newlines
    # remove comments
    # remove spaces around control characters,
    #   e.g. {  color : #fff  } ==> {color:#fff}
    # remove trailing semicolons
    echo "$1" \
    | tr "\n" " " \
    | perl -pe "s/\/\*.*?\*\///g" \
    | perl -pe "s/\s*([{}:;<>,])\s*/\1/g" \
    | perl -pe "s/;}/}/g"
}

# if a valid file is supplied, use it
if [ -f "$1" ]
then
    # we can minify that!
    minify "`cat $1`"
#if not, attempt to use the standard input
else
    # loop through the lines
    while read -r LINE
    do
        # store the line
        css=${css}${LINE}
    done
    # we can minify that!
    minify "${css}"
fi
