#!/bin/bash

# number of random bytes, default is 10
n=10

# if the byte count is present and makes sense, use it
if [[ $1 =~ ^[0-9]+$ ]]; then
    n=$1
fi

# loop while the random number is below the desired length
while [ ${#random} -lt $n ]
do
        # get a random alphanumeric string
        #   take $n bytes from /dev/urandom
        #   print only the printable characters
        #   remove all non-alphanumeric characters
        #   append it to the existing random string
        random=$random`hexdump -v -n $(($n*5))  -e '"%_p"' /dev/urandom | tr -Cd "[:alnum:]"`
        # $n*5 random characters are acquired because most have to be discarded
        # /dev/urandom, as opposed to /dev/random, is used so to speed up the execution,
        # see `man urandom` for more information
done
# output the random string upto the target length
echo -n ${random:0:$n}

