#!/bin/bash

# number of random bytes, default is 10
export n=10

# if the byte count is present and makes sense, use it
if [[ $1 =~ ^[0-9]+$ ]]; then
    export n=$1
fi

# magic
#   take the first $n bytes from /dev/random
#   convert them to base64
#   remove non-alphanumeric characters: / | = and newline
#   take $n bytes of the result
head -c $n /dev/random | base64 | tr -d "/+=\n" | head -c $n
echo
