#!/bin/bash

# where am I?
export system=`uname`

# argument must be alphanumeric, e.g. en0, eth1, etc.
if [[ $1 =~ ^[0-9a-z]+$ ]]; then
    # different commands for different systems
    case "$system" in
        Linux)  echo sudo ifconfig $1 hw ether `randomhex 6` ;;
        Darwin) echo sudo ifconfig $1    ether `randomhex 6` ;;
        *)      echo "$system is not supported" ;;
    esac
else
    echo "usage: randommac [device]"
fi

